In [1]:
#step1 numpyをインストール
import numpy as np

In [65]:
#step2　記述
A = np.array([[0,1],[2,3],[4,5]])#3行2列の多次元配列
B = np.array([[0,1,2,3],[4,5,6,7]])#2行3列の多次元配列

In [72]:
print(A)

[[0 1]
 [2 3]
 [4 5]]


In [71]:
print(B)

[[0 1 2 3]
 [4 5 6 7]]


In [66]:
#step3 演算
C = np.dot(A,B)

In [67]:
#step4 結果
print(C)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


In [69]:
#step4 最大値をもとめる
print(C.max())

47


In [50]:
print(f'これは{A}')
print(f'これは{B}')
print(f'これは{C}')

これは[[0 1 2]]
これは[[2 3 4]
 [4 5 6]]
これは[5 6 7]


In [49]:
A = np.array([[0,1,2]])
B = np.array([[2,3,4],[4,5,6]])
C = np.array([5,6,7])

In [51]:
print(A.shape)
print(B.shape)
print(C.shape)
print(A.ndim)
print(B.ndim)
print(C.ndim)

(1, 3)
(2, 3)
(3,)
2
2
1


In [56]:
print(a)#確認
print(b)

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2 3]
 [4 5 6 7]]


In [58]:
c = ([0,1],[2,3],[4,5])